controller_list:
  - name: fake_L_PELVIS_PALM_10DOF_controller
    joints:
      - back_bkz
      - back_bky
      - back_bkx
      - l_arm_shz
      - l_arm_shx
      - l_arm_ely
      - l_arm_elx
      - l_arm_wry
      - l_arm_wrx
      - l_arm_wry2
  - name: fake_R_PELVIS_PALM_10DOF_controller
    joints:
      - back_bkz
      - back_bky
      - back_bkx
      - r_arm_shz
      - r_arm_shx
      - r_arm_ely
      - r_arm_elx
      - r_arm_wry
      - r_arm_wrx
      - r_arm_wry2
  - name: fake_L_SHOULDER_HAND_7DOF_controller
    joints:
      - l_arm_shz
      - l_arm_shx
      - l_arm_ely
      - l_arm_elx
      - l_arm_wry
      - l_arm_wrx
      - l_arm_wry2
  - name: fake_R_SHOULDER_HAND_7DOF_controller
    joints:
      - r_arm_shz
      - r_arm_shx
      - r_arm_ely
      - r_arm_elx
      - r_arm_wry
      - r_arm_wrx
      - r_arm_wry2
  - name: fake_leftGripper_controller
    joints:
      - l_palm_finger_1_joint
      - l_finger_1_joint_1
      - l_finger_1_joint_2
      - l_finger_1_joint_3
      - l_finger_1_joint_paradistal_hinge
      - l_finger_1_joint_median_actuating_hinge
      - l_finger_1_joint_median_actuating_hinge_median_bar
      - l_finger_1_joint_paramedian_hinge
      - l_finger_1_joint_paramedian_hinge_median_bar_underactuated
      - l_finger_1_joint_paraproximal_actuating_hinge
      - l_finger_1_joint_paraproximal_bar
      - l_finger_1_joint_proximal_actuating_hinge
      - l_finger_1_joint_proximal_actuating_bar
      - l_palm_finger_2_joint
      - l_finger_2_joint_1
      - l_finger_2_joint_2
      - l_finger_2_joint_3
      - l_finger_2_joint_paradistal_hinge
      - l_finger_2_joint_median_actuating_hinge
      - l_finger_2_joint_median_actuating_hinge_median_bar
      - l_finger_2_joint_paramedian_hinge
      - l_finger_2_joint_paramedian_hinge_median_bar_underactuated
      - l_finger_2_joint_paraproximal_actuating_hinge
      - l_finger_2_joint_paraproximal_bar
      - l_finger_2_joint_proximal_actuating_hinge
      - l_finger_2_joint_proximal_actuating_bar
      - l_palm_finger_middle_joint
      - l_finger_middle_joint_1
      - l_finger_middle_joint_2
      - l_finger_middle_joint_3
      - l_finger_middle_joint_paradistal_hinge
      - l_finger_middle_joint_median_actuating_hinge
      - l_finger_middle_joint_median_actuating_hinge_median_bar
      - l_finger_middle_joint_paramedian_hinge
      - l_finger_middle_joint_paramedian_hinge_median_bar_underactuated
      - l_finger_middle_joint_paraproximal_actuating_hinge
      - l_finger_middle_joint_paraproximal_bar
      - l_finger_middle_joint_proximal_actuating_hinge
      - l_finger_middle_joint_proximal_actuating_bar
  - name: fake_rightGripper_controller
    joints:
      - r_palm_finger_1_joint
      - r_finger_1_joint_1
      - r_finger_1_joint_2
      - r_finger_1_joint_3
      - r_finger_1_joint_paradistal_hinge
      - r_finger_1_joint_median_actuating_hinge
      - r_finger_1_joint_median_actuating_hinge_median_bar
      - r_finger_1_joint_paramedian_hinge
      - r_finger_1_joint_paramedian_hinge_median_bar_underactuated
      - r_finger_1_joint_paraproximal_actuating_hinge
      - r_finger_1_joint_paraproximal_bar
      - r_finger_1_joint_proximal_actuating_hinge
      - r_finger_1_joint_proximal_actuating_bar
      - r_palm_finger_2_joint
      - r_finger_2_joint_1
      - r_finger_2_joint_2
      - r_finger_2_joint_3
      - r_finger_2_joint_paradistal_hinge
      - r_finger_2_joint_median_actuating_hinge
      - r_finger_2_joint_median_actuating_hinge_median_bar
      - r_finger_2_joint_paramedian_hinge
      - r_finger_2_joint_paramedian_hinge_median_bar_underactuated
      - r_finger_2_joint_paraproximal_actuating_hinge
      - r_finger_2_joint_paraproximal_bar
      - r_finger_2_joint_proximal_actuating_hinge
      - r_finger_2_joint_proximal_actuating_bar
      - r_palm_finger_middle_joint
      - r_finger_middle_joint_1
      - r_finger_middle_joint_2
      - r_finger_middle_joint_3
      - r_finger_middle_joint_paradistal_hinge
      - r_finger_middle_joint_median_actuating_hinge
      - r_finger_middle_joint_median_actuating_hinge_median_bar
      - r_finger_middle_joint_paramedian_hinge
      - r_finger_middle_joint_paramedian_hinge_median_bar_underactuated
      - r_finger_middle_joint_paraproximal_actuating_hinge
      - r_finger_middle_joint_paraproximal_bar
      - r_finger_middle_joint_proximal_actuating_hinge
      - r_finger_middle_joint_proximal_actuating_bar