controller_list:
  - name: fake_L_PELVIS_PALM_10DOF_controller
    joints:
      - back_bkz
      - back_bky
      - back_bkx
      - l_arm_shz
      - l_arm_shx
      - l_arm_ely
      - l_arm_elx
      - l_arm_wry
      - l_arm_wrx
      - l_arm_wry2
      - l_fixed
  - name: fake_R_PELVIS_PALM_10DOF_controller
    joints:
      - back_bkz
      - back_bky
      - back_bkx
      - r_arm_shz
      - r_arm_shx
      - r_arm_ely
      - r_arm_elx
      - r_arm_wry
      - r_arm_wrx
      - r_arm_wry2
      - r_fixed
  - name: fake_L_SHOULDER_HAND_7DOF_controller
    joints:
      - l_arm_shz
      - l_arm_shx
      - l_arm_ely
      - l_arm_elx
      - l_arm_wry
      - l_arm_wrx
      - l_arm_wry2
      - l_fixed
  - name: fake_R_SHOULDER_HAND_7DOF_controller
    joints:
      - r_arm_shz
      - r_arm_shx
      - r_arm_ely
      - r_arm_elx
      - r_arm_wry
      - r_arm_wrx
      - r_arm_wry2
      - r_fixed
  - name: fake_LEFT_GRIPPER_controller
    joints:
      - l_fixed
      - l_fixed_dummy
      - l_fixed_dummy2
      - l_palm_to_finger_1_1
      - l_finger_1_1_to_finger_1_2
      - l_finger_1_2_to_finger_1_3
      - l_palm_to_finger_2_1
      - l_finger_2_1_to_finger_2_2
      - l_finger_2_2_to_finger_2_3
      - l_palm_to_finger_3_1
      - l_finger_3_1_to_finger_3_2
      - l_finger_3_2_to_finger_3_3
  - name: fake_RIGHT_GRIPPER_controller
    joints:
      - r_fixed
      - r_fixed_dummy
      - r_fixed_dummy2
      - r_palm_to_finger_1_1
      - r_finger_1_1_to_finger_1_2
      - r_finger_1_2_to_finger_1_3
      - r_palm_to_finger_2_1
      - r_finger_2_1_to_finger_2_2
      - r_finger_2_2_to_finger_2_3
      - r_palm_to_finger_3_1
      - r_finger_3_1_to_finger_3_2
      - r_finger_3_2_to_finger_3_3