controller_list:
  - name: fake_L_SHOULDER_HAND_7DOF_controller
    joints:
      - leftShoulderPitch
      - leftShoulderRoll
      - leftShoulderYaw
      - leftElbowPitch
      - leftForearmYaw
      - leftWristRoll
      - leftWristPitch
      - leftMiddleFingerPitch1
  - name: fake_R_SHOULDER_HAND_7DOF_controller
    joints:
      - rightShoulderPitch
      - rightShoulderRoll
      - rightShoulderYaw
      - rightElbowPitch
      - rightForearmYaw
      - rightWristRoll
      - rightWristPitch
      - rightMiddleFingerPitch1
  - name: fake_R_PELVIS_PALM_10DOF_controller
    joints:
      - torsoYaw
      - torsoPitch
      - torsoRoll
      - rightShoulderPitch
      - rightShoulderRoll
      - rightShoulderYaw
      - rightElbowPitch
      - rightForearmYaw
      - rightWristRoll
      - rightWristPitch
      - rightMiddleFingerPitch1
  - name: fake_L_PELVIS_PALM_10DOF_controller
    joints:
      - torsoYaw
      - torsoPitch
      - torsoRoll
      - leftShoulderPitch
      - leftShoulderRoll
      - leftShoulderYaw
      - leftElbowPitch
      - leftForearmYaw
      - leftWristRoll
      - leftWristPitch
      - leftMiddleFingerPitch1