valkyrie:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - virtual_joint
      - leftHipYaw
      - leftHipRoll
      - leftHipPitch
      - leftKneePitch
      - leftAnklePitch
      - leftAnkleRoll
      - rightHipYaw
      - rightHipRoll
      - rightHipPitch
      - rightKneePitch
      - rightAnklePitch
      - rightAnkleRoll
      - torsoYaw
      - torsoPitch
      - torsoRoll
      - leftShoulderPitch
      - leftShoulderRoll
      - leftShoulderYaw
      - leftElbowPitch
      - leftForearmYaw
      - leftWristRoll
      - leftWristPitch
      - leftIndexFingerPitch1
      - leftIndexFingerPitch2
      - leftIndexFingerPitch3
      - leftMiddleFingerPitch1
      - leftMiddleFingerPitch2
      - leftMiddleFingerPitch3
      - leftPinkyPitch1
      - leftPinkyPitch2
      - leftPinkyPitch3
      - leftThumbRoll
      - leftThumbPitch1
      - leftThumbPitch2
      - leftThumbPitch3
      - lowerNeckPitch
      - neckYaw
      - upperNeckPitch
      - hokuyo_joint
      - rightShoulderPitch
      - rightShoulderRoll
      - rightShoulderYaw
      - rightElbowPitch
      - rightForearmYaw
      - rightWristRoll
      - rightWristPitch
      - rightIndexFingerPitch1
      - rightIndexFingerPitch2
      - rightIndexFingerPitch3
      - rightMiddleFingerPitch1
      - rightMiddleFingerPitch2
      - rightMiddleFingerPitch3
      - rightPinkyPitch1
      - rightPinkyPitch2
      - rightPinkyPitch3
      - rightThumbRoll
      - rightThumbPitch1
      - rightThumbPitch2
      - rightThumbPitch3
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    []